apiVersion: storage.gcp.upbound.io/v1beta1
kind: Notification
metadata:
  annotations:
    meta.upbound.io/example-id: storage/v1beta1/notification
  labels:
    testing.upbound.io/example-name: notification
  name: notification
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: bucket
    customAttributes:
      new-attribute: new-attribute-value
    eventTypes:
    - OBJECT_FINALIZE
    - OBJECT_METADATA_UPDATE
    payloadFormat: JSON_API_V1
    topicSelector:
      matchLabels:
        testing.upbound.io/example-name: topic

---

apiVersion: pubsub.gcp.upbound.io/v1beta1
kind: Topic
metadata:
  annotations:
    meta.upbound.io/example-id: storage/v1beta1/notification
  labels:
    testing.upbound.io/example-name: topic
  name: topic
spec:
  forProvider: {}

---

apiVersion: pubsub.gcp.upbound.io/v1beta1
kind: TopicIAMMember
metadata:
  annotations:
    meta.upbound.io/example-id: pubsub/v1beta1/topiciamgcsmember
  labels:
    testing.upbound.io/example-name: topic-iam-gcs-member
  name: topic-iam-gcs-member
spec:
  forProvider:
    member: "serviceAccount:service-${data.cloudplatform_project.projectNumber}@gs-project-accounts.iam.gserviceaccount.com"
    role: "roles/pubsub.publisher"
    topicSelector:
      matchLabels:
        testing.upbound.io/example-name: topic

---

apiVersion: storage.gcp.upbound.io/v1beta1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: storage/v1beta1/notification
  labels:
    testing.upbound.io/example-name: bucket
  name: bucket
spec:
  forProvider:
    location: US